from typing import Optional

class BC7CompressBlockParams:
    m_mode_mask: int
    m_max_partitions: int
    m_weights: list[int]
    m_uber_level: int
    m_perceptual: bool
    m_try_least_squares: bool
    m_mode17_partition_estimation_filterbank: bool
    m_force_selectors: bool
    m_force_alpha: bool
    m_quant_mode6_endpoints: bool
    m_bias_mode1_pbits: bool
    m_pbit1_weight: float
    m_mode1_error_weight: float
    m_mode5_error_weight: float
    m_mode6_error_weight: float
    m_mode7_error_weight: float

    def __init__(self) -> None: ...
    def init_linear_weights(self) -> None: ...
    def init_perceptual_weights(self) -> None: ...

def compress_bc1(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc1_dither(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc3(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc4(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc5(data: bytes, width: int, height: int) -> bytes: ...
def compress_bc7(data: bytes, width: int, height: int, params: Optional[BC7CompressBlockParams] = None) -> bytes: ...
def compress_etc1_rgb(data: bytes, width: int, height: int) -> bytes: ...
def compress_etc1_rgb_dither(data: bytes, width: int, height: int) -> bytes: ...
def compress_etc2_rgb(data: bytes, width: int, height: int) -> bytes: ...
def compress_etc2_rgba(data: bytes, width: int, height: int) -> bytes: ...
def compress_eac_r(data: bytes, width: int, height: int) -> bytes: ...
def compress_eac_rg(data: bytes, width: int, height: int) -> bytes: ...
def decompress_etc1_rgb(data: bytes, width: int, height: int) -> bytes: ...
def decompress_etc2_rgb(data: bytes, width: int, height: int) -> bytes: ...
def decompress_etc2_rgba(data: bytes, width: int, height: int) -> bytes: ...
def decompress_etc2_r11(data: bytes, width: int, height: int) -> bytes: ...
def decompress_etc2_rg11(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc1(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc3(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc4(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc5(data: bytes, width: int, height: int) -> bytes: ...
def decompress_bc7(data: bytes, width: int, height: int) -> bytes: ...
